@echo off
compilerdriver main1.src
compilerdriver main2.src
compilerdriver main3.src
compilerdriver main5.src
compilerdriver main6.src
compilerdriver polynomial.src
compilerdriver bubblesort.src
compilerdriver simplemain.src
